# write golang workflow
name: generate golang unit tests

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-20.04

    steps:
      - name: setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: checkout
        uses: actions/checkout@v3

      - name: generate
        run: |
          go install github.com/lkeix/go-test-generator/cmd/go-test-generator@v1.0.1 
          go-test-generator
          cat ./generator_test.go
